version: '3.8'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hello.html:/var/www/html/taxinder/index.html
    ports:
      - 8080:80

  api:
    build: https://github.com/kluchi/taxinder-api.git
    environment:
      - API_BASE_PATH=/taxinder
