version: '3.8'
services:
  root_nginx:
    container_name: root_nginx
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROXY_BASE_PATH=${PROXY_BASE_PATH-/}
    ports:
      - ${ROOT_NGINX_PORT-8080}:80
    depends_on:
      # mention every host we try to resolve in our nginx.conf
      - api
      - frontend

  api:
    container_name: main_api_server
    build: https://github.com/kluchi/taxinder-api.git
    environment:
      - API_BASE_PATH=${PROXY_BASE_PATH-/}

  frontend:
    container_name: frontend_server
    build: https://github.com/kluchi/taxinder-frontend.git
    environment:
      - FRONT_BASE_PATH=${PROXY_BASE_PATH-/}
