name: Docker Compose Actions Workflow
on:
  schedule:
    - cron: "1 0 * * *"
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install necessary tool versions
        run: apt update && apt remove docker-compose && pip install docker-compose
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:root_nginx appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/taxinder/
